plugins {
    id 'com.android.application'
}

android {
    namespace 'com.franluz.homedecor'
    compileSdk 36

    defaultConfig {
        applicationId 'com.franluz.homedecor'
        minSdk 23
        targetSdk 36
        versionCode 28800
        versionName '2.8.8'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
