plugins {
    id 'com.android.application'
}

android {
    namespace 'com.timachado.bibliaebd'
    compileSdk 36

    defaultConfig {
        applicationId 'com.timachado.bibliaebd'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix '-teste'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
