plugins {
    id 'com.android.application'
}

android {
    namespace 'com.timachado.bibliaebd'
    compileSdk 36

    defaultConfig {
        applicationId 'com.timachado.bibliaebd'
        minSdk 24
        targetSdk 36
        versionCode 112
        versionName '1.15.3'
    }

    signingConfigs {
        debug {
            storeFile file('test-signing.jks')
            storePassword 'BibliaEBD-Test-2026'
            keyAlias 'bibliaebd-test'
            keyPassword 'BibliaEBD-Test-2026'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.debug
            applicationIdSuffix ''
            versionNameSuffix '-teste'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
