plugins {
    id 'com.android.application'
}

android {
    namespace 'com.franluz.seller'
    compileSdk 36

    defaultConfig {
        applicationId 'com.franluz.seller'
        minSdk 26
        targetSdk 36
        versionCode 10101
        versionName '1.1.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
