plugins {
    id 'com.android.application'
}

android {
    namespace 'com.franluz.seller'
    compileSdk 36

    defaultConfig {
        applicationId 'com.franluz.seller'
        minSdk 23
        targetSdk 36
        versionCode 21001
        versionName '2.1.1'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.7.3'
}
